library: library.db
directory: ~/MusicLib

import:
    # delete files on import? (by default -- maybe a bad option considering this is also a cli flag)
    move: no
    # resume interrupted imports. "ask" by default.
    resume: yes
    # in -q (quiet) mode, what is the fallback -- slip/asis. Skip is default.
    quiet_fallback: skip
    # default: no log
    log: ~/.beets.log
    # beets uses directories to guess albums by default. Use tags instead?
    # # Useful for poory organised incoming music. No by default
    group_albums: yes
    duplicate_action: skip
    bell: no

# When moving files beets will remove empty directories, or directories
# containing just these files.
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg", "*.png*", "*.nfo"]
ignore: [".*", "*~", "System Volume Information", "lost+found"]

plugins: []
pluginpath: []
