library: library.db
directory: ~/MusicLib

import:
    # delete files on import? Not by default. If you want this use
    move: no
    # resume interrupted imports. "ask" by default.
    resume: yes
    # in -q (quiet) mode, what is the fallback -- slip/asis. Skip is default.
    quiet_fallback: skip
    # beets uses directories to guess albums by default. Use tags instead?
    # # Useful for poory organised incoming music. No by default
    group_albums: yes
    duplicate_action: skip
    bell: no

# When moving files beets will remove empty directories, or directories
# containing just these files.
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg", "*.png*", "*.nfo"]
ignore: [".*", "*~", "System Volume Information", "lost+found"]

# see https://beets.readthedocs.io/en/stable/plugins/
# there are many more useful plugins
plugins:
  # database of acoustic metadata such as chord key, bpm
  - acousticbrainz
  # guess from filename if there are no tags. User must confirm.
  - fromfilename
  # edit tags with $EDITOR
  - edit
  # identify tag-less songs with chromaprint. Dependencies
  # - chromaprint
  # find the chord key. acousticbrainz is probably a better
  # source but won't have every song. Requires keyfinder.
  #- keyfinder
pluginpath: []
